name: "Build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze Dart
        run: flutter analyze
        # uses: zgosalvez/github-actions-analyze-dart@v1
